--Name- Gurpreet Singh, Student no. 7557259

CREATE DATABASE AUTOPARTS;


CREATE TABLE PLANT (PLANT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
					PLANT_NAME VARCHAR(255));

CREATE TABLE EMPLOYEE (EMPLOYEE_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
						FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255),
						ADDRESS VARCHAR(255), PHONE CHAR(10),
						PLANT_ID INT,
						CONSTRAINT EMPLOYEE_FK FOREIGN KEY(PLANT_ID) REFERENCES PLANT(PLANT_ID) ON DELETE CASCADE);

CREATE TABLE CUSTOMER (CUSTOMER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
						CUSTOMER_NAME VARCHAR(255));

CREATE TABLE PARTSNAME (PARTSNAME_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
						PARTSNAME_NAME VARCHAR(255));

CREATE TABLE PARTSNUMBER (PARTSNUMBER_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY, PARTS_NO VARCHAR(255),
							PARTSNAME_ID INT,
							CONSTRAINT PARTSNUMBER_FK FOREIGN KEY(PARTSNAME_ID) REFERENCES PARTSNAME(PARTSNAME_ID) ON DELETE CASCADE);

CREATE TABLE TIMETOMANUFCATURE ( TIMETOMANUFACTURE_TIME INT, CUSTOMER_ID INT, EMPLOYEE_ID INT, PARTSNUMBER_ID INT
								CONSTRAINT TIMETOMANUFACTURE_CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
								CONSTRAINT TIMETOMANUFACTURE_EMPLOYEE_ID_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
								CONSTRAINT TIMETOMANUFACTURE_PARTSNAME_ID_FK FOREIGN KEY(PARTSNUMBER_ID) REFERENCES PARTSNUMBER(PARTSNUMBER_ID) ON DELETE CASCADE,
								CONSTRAINT TIMETOMANUFACTURE_FK PRIMARY KEY (PARTSNUMBER_ID, CUSTOMER_ID, EMPLOYEE_ID));

PRINT 'INSERTING VALUES'

INSERT INTO PLANT (PLANT_NAME)
VALUES ('GUELPH');
INSERT INTO PLANT (PLANT_NAME)
VALUES ('WATERLOO');

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ADDRESS, PHONE, PLANT_ID)
VALUES ('JOE', 'SINGH', '183 CEDARBRAE AVE. WATERLOO ON N2L4S8',6477956165,01);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ADDRESS, PHONE, PLANT_ID)
VALUES ('FRAMK', 'SAM', '221 FALLING CRES. WATERLOO ON N2L5S8',5195658941,02);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ADDRESS, PHONE, PLANT_ID)
VALUES ('MARY', 'DIETRICH', '555 HAVLELOCK DR. WATERLOO ON N2L4S8',5195689956,02);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ADDRESS, PHONE, PLANT_ID)
VALUES ('GARY', 'FERRERO', '1526 WEBER ST. WATERLOO ON N2L5C2',5195263326,01);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ADDRESS, PHONE, PLANT_ID)
VALUES ('JOHN', 'KUMAR', '225 LANCASTER ST. KITCHENER ON N2L3G3',647445113,02);


INSERT INTO CUSTOMER(CUSTOMER_NAME)
VALUES ('SUZUKI');
INSERT INTO CUSTOMER(CUSTOMER_NAME)
VALUES ('BMW');


INSERT INTO PARTSNAME(PARTSNAME_NAME)
VALUES ('CRANKSHAFT');
INSERT INTO PARTSNAME(PARTSNAME_NAME)
VALUES ('PISTON');
INSERT INTO PARTSNAME(PARTSNAME_NAME)
VALUES ('EXHAUST');


INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('MOTO001', 1);
INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('MOTO002', 2);
INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('CAR001', 2);
INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('CAR002', 3);
INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('MOTO003', 3);
INSERT INTO PARTSNUMBER(PARTS_NO, PARTSNAME_ID)
VALUES ('CAR003', 1);


INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (45,1,1,1);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (40,1,2,1);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (20,1,1,2);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (15,1,3,3);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (20,2,3,3);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (10,2,3,2);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (65,2,4,1);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (110,2,4,4);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (45,1,5,5);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (25,1,5,6);
INSERT INTO TIMETOMANUFCATURE(TIMETOMANUFACTURE_TIME, CUSTOMER_ID,EMPLOYEE_ID,PARTSNUMBER_ID)
VALUES (45,2,2,6);

PRINT ' QUESTION 6 A'

CREATE VIEW PARTSNUMBER_PARTSNAME_VW AS
SELECT PN.PARTSNUMBER_ID, PN.PARTS_NO, P.PARTSNAME_ID, P.PARTSNAME_NAME FROM PARTSNUMBER PN INNER JOIN PARTSNAME P
		ON PN.PARTSNAME_ID = P.PARTSNAME_ID;

SELECT (SELECT CUSTOMER_NAME FROM CUSTOMER C WHERE C.CUSTOMER_ID = TIMETOMANUFCATURE.CUSTOMER_ID) AS [CUTOMER],
		(SELECT PARTSNAME_NAME FROM PARTSNUMBER_PARTSNAME_VW AS PV WHERE PV.PARTSNUMBER_ID = TIMETOMANUFCATURE.PARTSNUMBER_ID) AS [JOB],
		TIMETOMANUFACTURE_TIME
		FROM TIMETOMANUFCATURE 
		WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_NAME = 'SUZUKI');

PRINT 'QUESTION 6B'

CREATE VIEW PLANT_EMPLOYEE_VW AS
SELECT P.PLANT_ID, P.PLANT_NAME, E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.ADDRESS, E.PHONE FROM PLANT AS P 
	INNER JOIN EMPLOYEE E
	ON P.PLANT_ID = E.PLANT_ID;

SELECT * FROM PARTSNUMBER_PARTSNAME_VW WHERE PARTSNUMBER_ID IN
(SELECT PARTSNUMBER_ID FROM TIMETOMANUFCATURE WHERE EMPLOYEE_ID IN
(SELECT EMPLOYEE_ID FROM PLANT_EMPLOYEE_VW WHERE PLANT_NAME = 'WATERLOO'));

